### ISSUE TITLE
Make Maxmind GeoIP license optional

### ISSUE THREAD

**Issue by duese22** [litinoveweedle/hassio-addons#7]
Please make the option of Maxmind GeoIP license optional. As i don't need the lookup and will not buy a license.
But i would be happy to have the in-out data visualized in my HA.
S6-rc interupts the start of the container if no key is present as far as i understand: ntopng/rootfs/etc/s6-overlay/s6-rc.d/init-geoip/run

`[10:26:38] INFO: Updating Maxmind Database...
error retrieving updates: error while getting database for GeoLite2-ASN: unexpected HTTP status code: received HTTP status code: 401: Your account ID or license key could not be authenticated.
s6-rc: warning: unable to start service init-geoip: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.`

Thank you for the plugin!

**Comment by litinoveweedle** [comment]
HI, thank for report. As I am really lame with hassio addons, it took several try & test versions, but I think it was fixed in the 0.0.24 finally.

There is one glitch you can face in the way how hassio stores addon config, where there was already any (even empty) value stored in the now 'optional' parameter. To fix it you have to fill something (really anything) in the config field, save it and then delete the value and save it again. You will then see optional parameter to disappear and be visible only when you toggle 'Show unused optional configuration options'. Do this procedure for 'export flows', 'geoip account id' and 'geoip license key'.

Please test it and report back if the issue was fixed, thanks.

**Comment by litinoveweedle** [comment]
fixed in v0.0.24
